# Generated by Django 4.2.4 on 2023-08-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('losses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Headers',
            new_name='Header',
        ),
    ]
